project:
  type: website

website:
  title: "ISSS608-DC"
  navbar:
    left:
    - text: "Hands-on Exercises"
      menu:
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-On_Ex02.html"
        - text: "Hands-on Exercise 3A"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-On_Ex03a.html"
        - text: "Hands-on Exercise 3B"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-On_Ex03b.html"
        - text: "Hands-on Exercise 4A"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-On_Ex04a.html"
        - text: "Hands-on Exercise 4B"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-On_Ex04b.html"
        - text: "Hands-on Exercise 4C"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-On_Ex04c.html"
        - text: "Hands-on Exercise 4D"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-On_Ex04d.html"
        - text: "Hands-on Exercise 5A"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-On_Ex05a.html"
        - text: "Hands-on Exercise 5B"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-On_Ex05b.html"
        - text: "Hands-on Exercise 5C"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-On_Ex05c.html"
        - text: "Hands-on Exercise 5D"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-On_Ex05d.html"
        - text: "Hands-on Exercise 5E"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-On_Ex05e.html"
        - text: "Hands-on Exercise 6"
          href: "Hands-on_Ex/Hands-on_Ex06/Hands-On_Ex06.html"
    - text: "Take-Home Exercises"
      menu:
        - text: "Take-Home Exercise 1"
          href: "Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01.html"
        - text: "Take-Home Exercise 2"
          href: "Take-Home_Ex/Take-Home_Ex02/Take-Home_Ex02.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true


editor: visual




