project:
  type: website

website:
  title: "ISSS608-DC"
  navbar:
    left:
    - text: "Hands-on Exercises"
      menu:
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-On_Ex02.html"
        - text: "Hands-on Exercise 3A"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-On_Ex03a.html"
        - text: "Hands-on Exercise 3B"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-On_Ex03b.html"
        - text: "Hands-on Exercise 4"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-On_Ex04.html"
    - text: "Take-Home Exercises"
      menu:
        - text: "Take-Home Exercise 1"
          href: "Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

