project:
  type: website

website:
  title: "ISSS608-DC"
  navbar:
    left:
    - text: "Hands-on Exercises"
      menu:
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-On_Ex02.html"
        - text: "Hands-on Exercise 3A"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-On_Ex03a.html"
        - text: "Hands-on Exercise 3B"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-On_Ex03b.html"
        - text: "Hands-on Exercise 4A"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-On_Ex04a.html"
        - text: "Hands-on Exercise 4B"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-On_Ex04b.html"
        - text: "Hands-on Exercise 4C"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-On_Ex04c.html"
        - text: "Hands-on Exercise 4D"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-On_Ex04d.html"
        - text: "Hands-on Exercise 5"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-On_Ex05.html"
        - text: "Hands-on Exercise 6"
          href: "Hands-on_Ex/Hands-on_Ex06/Hands-On_Ex06.html"
        - text: "Hands-on Exercise 7"
          href: "Hands-on_Ex/Hands-on_Ex07/Hands-On_Ex07.html"
        - text: "Hands-on Exercise 8a"
          href: "Hands-on_Ex/Hands-on_Ex08/Hands-On_Ex08a.html"
        - text: "Hands-on Exercise 8b"
          href: "Hands-on_Ex/Hands-on_Ex08/Hands-On_Ex08b.html"          
        - text: "Hands-on Exercise 8c"
          href: "Hands-on_Ex/Hands-on_Ex08/Hands-On_Ex08c.html"          
        - text: "Hands-on Exercise 9a"
          href: "Hands-on_Ex/Hands-on_Ex09/Hands-On_Ex09a.html"
        - text: "Hands-on Exercise 9b"
          href: "Hands-on_Ex/Hands-on_Ex09/Hands-On_Ex09b.html"
        - text: "Hands-on Exercise 9c"
          href: "Hands-on_Ex/Hands-on_Ex09/Hands-On_Ex09c.html"
        - text: "Hands-on Exercise 9d"
          href: "Hands-on_Ex/Hands-on_Ex09/Hands-On_Ex09d.html"
        - text: "Hands-on Exercise 9e"
          href: "Hands-on_Ex/Hands-on_Ex09/Hands-On_Ex09e.html"
    - text: "Take-Home Exercises"
      menu:
        - text: "Take-Home Exercise 1 (Part 1 - Own Visualisation)"
          href: "Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01.html"
        - text: "Take-Home Exercise 1 (Part 2 - Liu Chih Yuan's Visualisation)"
          href: "Take-Home_Ex/Take-Home_Ex01/TakeHome_Ex01_LCY.html"
        - text: "Take-Home Exercise 2"
          href: "Take-Home_Ex/Take-Home_Ex02/Take-Home_Ex02_MC3.html"
        - text: "Take-Home Exercise 3"
          href: "Take-Home_Ex/Take-Home_Ex03/Take-Home_Ex03.html"
    - text: "In-Class Exercises"
      menu:
        - text: "Exercise 1 (on Mini Challenge 1 data)"
          href: "In-Class_Ex/In-Class_Ex01/In-Class_Ex01.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true


editor: visual




