---
title: "Investment Vis"
author: ""
format: dashboard
theme: 
  - darkly
execute: 
  echo: false
editor: visual
---

```{r}
pacman::p_load(tidyverse, tidyquant, 
               timetk, plotly, glue)
```

```{r}
SGStock <- read.csv("data/SGStock.csv")
```

```{r}
daily_prices <- SGStock %>%
  select(Symbol) %>%
  tq_get(get = "stock.prices",
         from = "2025-01-01",
         to = Sys.Date())

daily_prices <- daily_prices %>%
  left_join(SGStock)
```

# DBS

```{r}
start_date <- min(daily_prices$date)
end_date <- max(daily_prices$date)
```

## Row {height="20%"}

```{r}
daily_summary <- daily_prices %>%
  filter(Symbol == "D05.SI" &
          date == end_date)
```

```{r}
#| content: valuebox
#| title: "Opening Price"
list(colour = "primary",
     value = daily_summary$open
)
```

```{r}
#| content: valuebox
#| title: "Closing Price"
list(colour = "primary",
     value = daily_summary$close
)
```

```{r}
#| content: valuebox
#| title: "Daily High"
list(colour = "primary",
     value = daily_summary$high
)
```

```{r}
#| content: valuebox
#| title: "Daily Low"
list(colour = "primary",
     value = daily_summary$low
)
```

## Row

```{r}
# Preparing the data
df <- daily_prices %>%
  filter(Name == "DBS Group")
 
mean_close <- mean(df$close, na.rm = TRUE)
sd_close <- sd(df$close, na.rm = TRUE)
ucl <- mean_close + 1 * sd_close
lcl <- mean_close - 1 * sd_close
 
df <- df %>%
  mutate(flag = case_when(
    close > ucl ~ "Above UCL",
    close < lcl ~ "Below LCL",
    TRUE ~ "Within Limits"))
 
mean_lbl <- paste0("Mean: ", round(mean_close, 2))
ucl_lbl <- paste0("UCL: ", round(ucl, 2))
lcl_lbl <- paste0("LCL: ", round(lcl,2))
 
start_lbl <- format(start_date, "%d %B %Y")
end_lbl <- format(end_date, "%d %B %Y")
start_lbl <- sub("^0", "", start_lbl)
end_lbl <- sub("^0", "", end_lbl)
dynamic_title <- glue("DBS Stock Prices from {start_lbl} to {end_lbl}")
```

```{r}
# Plotting stock price line hcart and the control chart +- 3 standard deviation form the mean
p <- ggplot(data = df, aes(x = date, y = close)) + 
  geom_line(colour = "steelblue") + 
  geom_hline(yintercept = mean_close, colour = "grey0", linetype = "dashed", size = 0.5, alpha = 0.8) + 
  geom_hline(yintercept = ucl, colour = "red", linetype = "dotted", size = 0.5, alpha = 0.8) + 
  geom_hline(yintercept = lcl, colour = "red", linetype = "dotted", size = 0.5, alpha = 0.8) + 
  geom_point(aes(colour = flag), size = 1) +
  annotate("text", x = min(df$date), y = ucl + 0.3, label = ucl_lbl, hjust = 0, colour = "red", size = 3.5) +
  annotate("text", x = min(df$date), y = lcl + 0.3, label = lcl_lbl, hjust = 0, colour = "red", size = 3.5) +
  annotate("text", x = min(df$date), y = mean_close, label = mean_lbl, hjust = 0, colour = "darkgreen", size = 3.5) +
scale_colour_manual(values = c("Above UCL" = "red", "Below LCL" = "red", "Within Limits" = "steelblue")) + 
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") + 
  labs(title = dynamic_title, y = "Closing Price", x = "") +
  theme_classic()
  
ggplotly(p)

```

```{r}

plot_ly(data = df,
       x = ~date,
       type = "candlestick",
       open = ~open,
       high = ~high,
       low = ~low,
       close = ~close,
       name = "prices") %>%
  add_lines(x = ~date,
            y = ~TTR::SMA(close, n = 5),
            name = "SMA 5",
            line = list(width = 1.5,
                        dash = "dot")) %>%
  add_lines(x = ~date,
            y = ~TTR::SMA(close, n = 15),
            name = "SMA 15",
            line = list(colour = "red",
                        width = 1.5)) %>%
  layout(title = "Technical Analysis of DBS Stock Prices",
         yaxis = list(title = "Closing Price"),
         xaxis = list(title = "Date"))

```
# UOB

```{r}
start_date <- min(daily_prices$date)
end_date <- max(daily_prices$date)
```

## Row {height="20%"}

```{r}
daily_summary <- daily_prices %>%
  filter(Symbol == "U11.SI" &
          date == end_date)
```

```{r}
#| content: valuebox
#| title: "Opening Price"
list(colour = "primary",
     value = daily_summary$open
)
```

```{r}
#| content: valuebox
#| title: "Closing Price"
list(colour = "primary",
     value = daily_summary$close
)
```

```{r}
#| content: valuebox
#| title: "Daily High"
list(colour = "primary",
     value = daily_summary$high
)
```

```{r}
#| content: valuebox
#| title: "Daily Low"
list(colour = "primary",
     value = daily_summary$low
)
```

## Row

```{r}
# Preparing the data
df <- daily_prices %>%
  filter(Name == "UOB")
 
mean_close <- mean(df$close, na.rm = TRUE)
sd_close <- sd(df$close, na.rm = TRUE)
ucl <- mean_close + 1 * sd_close
lcl <- mean_close - 1 * sd_close
 
df <- df %>%
  mutate(flag = case_when(
    close > ucl ~ "Above UCL",
    close < lcl ~ "Below LCL",
    TRUE ~ "Within Limits"))
 
mean_lbl <- paste0("Mean: ", round(mean_close, 2))
ucl_lbl <- paste0("UCL: ", round(ucl, 2))
lcl_lbl <- paste0("LCL: ", round(lcl,2))
 
start_lbl <- format(start_date, "%d %B %Y")
end_lbl <- format(end_date, "%d %B %Y")
start_lbl <- sub("^0", "", start_lbl)
end_lbl <- sub("^0", "", end_lbl)
dynamic_title <- glue("UOB Stock Prices from {start_lbl} to {end_lbl}")
```

```{r}
# Plotting stock price line hcart and the control chart +- 3 standard deviation form the mean
p <- ggplot(data = df, aes(x = date, y = close)) + 
  geom_line(colour = "steelblue") + 
  geom_hline(yintercept = mean_close, colour = "grey0", linetype = "dashed", size = 0.5, alpha = 0.8) + 
  geom_hline(yintercept = ucl, colour = "red", linetype = "dotted", size = 0.5, alpha = 0.8) + 
  geom_hline(yintercept = lcl, colour = "red", linetype = "dotted", size = 0.5, alpha = 0.8) + 
  geom_point(aes(colour = flag), size = 1) +
  annotate("text", x = min(df$date), y = ucl + 0.3, label = ucl_lbl, hjust = 0, colour = "red", size = 3.5) +
  annotate("text", x = min(df$date), y = lcl + 0.3, label = lcl_lbl, hjust = 0, colour = "red", size = 3.5) +
  annotate("text", x = min(df$date), y = mean_close, label = mean_lbl, hjust = 0, colour = "darkgreen", size = 3.5) +
scale_colour_manual(values = c("Above UCL" = "red", "Below LCL" = "red", "Within Limits" = "steelblue")) + 
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") + 
  labs(title = dynamic_title, y = "Closing Price", x = "") +
  theme_classic()
  
ggplotly(p)

```
```{r}

plot_ly(data = df,
       x = ~date,
       type = "candlestick",
       open = ~open,
       high = ~high,
       low = ~low,
       close = ~close,
       name = "prices") %>%
  add_lines(x = ~date,
            y = ~TTR::SMA(close, n = 5),
            name = "SMA 5",
            line = list(width = 1.5,
                        dash = "dot")) %>%
  add_lines(x = ~date,
            y = ~TTR::SMA(close, n = 15),
            name = "SMA 15",
            line = list(colour = "red",
                        width = 1.5)) %>%
  layout(title = "Technical Analysis of UOB Stock Prices",
         yaxis = list(title = "Closing Price"),
         xaxis = list(title = "Date"))

```

# SingTel

```{r}
start_date <- min(daily_prices$date)
end_date <- max(daily_prices$date)
```

## Row {height="20%"}

```{r}
daily_summary <- daily_prices %>%
  filter(Symbol == "Z74.SI" &
          date == end_date)
```

```{r}
#| content: valuebox
#| title: "Opening Price"
list(colour = "primary",
     value = daily_summary$open
)
```

```{r}
#| content: valuebox
#| title: "Closing Price"
list(colour = "primary",
     value = daily_summary$close
)
```

```{r}
#| content: valuebox
#| title: "Daily High"
list(colour = "primary",
     value = daily_summary$high
)
```

```{r}
#| content: valuebox
#| title: "Daily Low"
list(colour = "primary",
     value = daily_summary$low
)
```

## Row

```{r}
# Preparing the data
df <- daily_prices %>%
  filter(Name == "Singtel")
 
mean_close <- mean(df$close, na.rm = TRUE)
sd_close <- sd(df$close, na.rm = TRUE)
ucl <- mean_close + 1 * sd_close
lcl <- mean_close - 1 * sd_close
 
df <- df %>%
  mutate(flag = case_when(
    close > ucl ~ "Above UCL",
    close < lcl ~ "Below LCL",
    TRUE ~ "Within Limits"))
 
mean_lbl <- paste0("Mean: ", round(mean_close, 2))
ucl_lbl <- paste0("UCL: ", round(ucl, 2))
lcl_lbl <- paste0("LCL: ", round(lcl,2))
 
start_lbl <- format(start_date, "%d %B %Y")
end_lbl <- format(end_date, "%d %B %Y")
start_lbl <- sub("^0", "", start_lbl)
end_lbl <- sub("^0", "", end_lbl)
dynamic_title <- glue("Singtel Stock Prices from {start_lbl} to {end_lbl}")
```

```{r}
# Plotting stock price line hcart and the control chart +- 3 standard deviation form the mean
p <- ggplot(data = df, aes(x = date, y = close)) + 
  geom_line(colour = "steelblue") + 
  geom_hline(yintercept = mean_close, colour = "grey0", linetype = "dashed", size = 0.5, alpha = 0.8) + 
  geom_hline(yintercept = ucl, colour = "red", linetype = "dotted", size = 0.5, alpha = 0.8) + 
  geom_hline(yintercept = lcl, colour = "red", linetype = "dotted", size = 0.5, alpha = 0.8) + 
  geom_point(aes(colour = flag), size = 1) +
  annotate("text", x = min(df$date), y = ucl + 0.3, label = ucl_lbl, hjust = 0, colour = "red", size = 3.5) +
  annotate("text", x = min(df$date), y = lcl + 0.3, label = lcl_lbl, hjust = 0, colour = "red", size = 3.5) +
  annotate("text", x = min(df$date), y = mean_close, label = mean_lbl, hjust = 0, colour = "darkgreen", size = 3.5) +
scale_colour_manual(values = c("Above UCL" = "red", "Below LCL" = "red", "Within Limits" = "steelblue")) + 
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") + 
  labs(title = dynamic_title, y = "Closing Price", x = "") +
  theme_classic()
  
ggplotly(p)

```
```{r}

plot_ly(data = df,
       x = ~date,
       type = "candlestick",
       open = ~open,
       high = ~high,
       low = ~low,
       close = ~close,
       name = "prices") %>%
  add_lines(x = ~date,
            y = ~TTR::SMA(close, n = 5),
            name = "SMA 5",
            line = list(width = 1.5,
                        dash = "dot")) %>%
  add_lines(x = ~date,
            y = ~TTR::SMA(close, n = 15),
            name = "SMA 15",
            line = list(colour = "red",
                        width = 1.5)) %>%
  layout(title = "Technical Analysis of SingTel Stock Prices",
         yaxis = list(title = "Closing Price"),
         xaxis = list(title = "Date"))

```

# SIA

```{r}
start_date <- min(daily_prices$date)
end_date <- max(daily_prices$date)
```

## Row {height="20%"}

```{r}
daily_summary <- daily_prices %>%
  filter(Symbol == "C6L.SI" &
          date == end_date)
```

```{r}
#| content: valuebox
#| title: "Opening Price"
list(colour = "primary",
     value = daily_summary$open
)
```

```{r}
#| content: valuebox
#| title: "Closing Price"
list(colour = "primary",
     value = daily_summary$close
)
```

```{r}
#| content: valuebox
#| title: "Daily High"
list(colour = "primary",
     value = daily_summary$high
)
```

```{r}
#| content: valuebox
#| title: "Daily Low"
list(colour = "primary",
     value = daily_summary$low
)
```

## Row
```{r}
# Preparing the data
df <- daily_prices %>%
  filter(Name == "Singapore Airlines")
 
mean_close <- mean(df$close, na.rm = TRUE)
sd_close <- sd(df$close, na.rm = TRUE)
ucl <- mean_close + 1 * sd_close
lcl <- mean_close - 1 * sd_close
 
df <- df %>%
  mutate(flag = case_when(
    close > ucl ~ "Above UCL",
    close < lcl ~ "Below LCL",
    TRUE ~ "Within Limits"))
 
mean_lbl <- paste0("Mean: ", round(mean_close, 2))
ucl_lbl <- paste0("UCL: ", round(ucl, 2))
lcl_lbl <- paste0("LCL: ", round(lcl,2))
 
start_lbl <- format(start_date, "%d %B %Y")
end_lbl <- format(end_date, "%d %B %Y")
start_lbl <- sub("^0", "", start_lbl)
end_lbl <- sub("^0", "", end_lbl)
dynamic_title <- glue("Singapore Airlines Stock Prices from {start_lbl} to {end_lbl}")
```

```{r}
# Plotting stock price line hcart and the control chart +- 3 standard deviation form the mean
p <- ggplot(data = df, aes(x = date, y = close)) + 
  geom_line(colour = "steelblue") + 
  geom_hline(yintercept = mean_close, colour = "grey0", linetype = "dashed", size = 0.5, alpha = 0.8) + 
  geom_hline(yintercept = ucl, colour = "red", linetype = "dotted", size = 0.5, alpha = 0.8) + 
  geom_hline(yintercept = lcl, colour = "red", linetype = "dotted", size = 0.5, alpha = 0.8) + 
  geom_point(aes(colour = flag), size = 1) +
  annotate("text", x = min(df$date), y = ucl + 0.3, label = ucl_lbl, hjust = 0, colour = "red", size = 3.5) +
  annotate("text", x = min(df$date), y = lcl + 0.3, label = lcl_lbl, hjust = 0, colour = "red", size = 3.5) +
  annotate("text", x = min(df$date), y = mean_close, label = mean_lbl, hjust = 0, colour = "darkgreen", size = 3.5) +
scale_colour_manual(values = c("Above UCL" = "red", "Below LCL" = "red", "Within Limits" = "steelblue")) + 
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") + 
  labs(title = dynamic_title, y = "Closing Price", x = "") +
  theme_classic()
  
ggplotly(p)

```
```{r}

plot_ly(data = df,
       x = ~date,
       type = "candlestick",
       open = ~open,
       high = ~high,
       low = ~low,
       close = ~close,
       name = "prices") %>%
  add_lines(x = ~date,
            y = ~TTR::SMA(close, n = 5),
            name = "SMA 5",
            line = list(width = 1.5,
                        dash = "dot")) %>%
  add_lines(x = ~date,
            y = ~TTR::SMA(close, n = 15),
            name = "SMA 15",
            line = list(colour = "red",
                        width = 1.5)) %>%
  layout(title = "Technical Analysis of Singapore Airlines Stock Prices",
         yaxis = list(title = "Closing Price"),
         xaxis = list(title = "Date"))

```

# CapitalLand Mall Trust
```{r}
start_date <- min(daily_prices$date)
end_date <- max(daily_prices$date)
```

## Row {height="20%"}

```{r}
daily_summary <- daily_prices %>%
  filter(Symbol == "C38U.SI" &
          date == end_date)
```

```{r}
#| content: valuebox
#| title: "Opening Price"
list(colour = "primary",
     value = daily_summary$open
)
```

```{r}
#| content: valuebox
#| title: "Closing Price"
list(colour = "primary",
     value = daily_summary$close
)
```

```{r}
#| content: valuebox
#| title: "Daily High"
list(colour = "primary",
     value = daily_summary$high
)
```

```{r}
#| content: valuebox
#| title: "Daily Low"
list(colour = "primary",
     value = daily_summary$low
)
```
## Row
```{r}
# Preparing the data
df <- daily_prices %>%
  filter(Name == "CapitaLand Mall Trust")
 
mean_close <- mean(df$close, na.rm = TRUE)
sd_close <- sd(df$close, na.rm = TRUE)
ucl <- mean_close + 1 * sd_close
lcl <- mean_close - 1 * sd_close
 
df <- df %>%
  mutate(flag = case_when(
    close > ucl ~ "Above UCL",
    close < lcl ~ "Below LCL",
    TRUE ~ "Within Limits"))
 
mean_lbl <- paste0("Mean: ", round(mean_close, 2))
ucl_lbl <- paste0("UCL: ", round(ucl, 2))
lcl_lbl <- paste0("LCL: ", round(lcl,2))
 
start_lbl <- format(start_date, "%d %B %Y")
end_lbl <- format(end_date, "%d %B %Y")
start_lbl <- sub("^0", "", start_lbl)
end_lbl <- sub("^0", "", end_lbl)
dynamic_title <- glue("CapitaLand Mall Trust Stock Prices from {start_lbl} to {end_lbl}")
```

```{r}
# Plotting stock price line hcart and the control chart +- 3 standard deviation form the mean
p <- ggplot(data = df, aes(x = date, y = close)) + 
  geom_line(colour = "steelblue") + 
  geom_hline(yintercept = mean_close, colour = "grey0", linetype = "dashed", size = 0.5, alpha = 0.8) + 
  geom_hline(yintercept = ucl, colour = "red", linetype = "dotted", size = 0.5, alpha = 0.8) + 
  geom_hline(yintercept = lcl, colour = "red", linetype = "dotted", size = 0.5, alpha = 0.8) + 
  geom_point(aes(colour = flag), size = 1) +
  annotate("text", x = min(df$date), y = ucl + 0.3, label = ucl_lbl, hjust = 0, colour = "red", size = 3.5) +
  annotate("text", x = min(df$date), y = lcl + 0.3, label = lcl_lbl, hjust = 0, colour = "red", size = 3.5) +
  annotate("text", x = min(df$date), y = mean_close, label = mean_lbl, hjust = 0, colour = "darkgreen", size = 3.5) +
scale_colour_manual(values = c("Above UCL" = "red", "Below LCL" = "red", "Within Limits" = "steelblue")) + 
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") + 
  labs(title = dynamic_title, y = "Closing Price", x = "") +
  theme_classic()
  
ggplotly(p)

```
```{r}

plot_ly(data = df,
       x = ~date,
       type = "candlestick",
       open = ~open,
       high = ~high,
       low = ~low,
       close = ~close,
       name = "prices") %>%
  add_lines(x = ~date,
            y = ~TTR::SMA(close, n = 5),
            name = "SMA 5",
            line = list(width = 1.5,
                        dash = "dot")) %>%
  add_lines(x = ~date,
            y = ~TTR::SMA(close, n = 15),
            name = "SMA 15",
            line = list(colour = "red",
                        width = 1.5)) %>%
  layout(title = "Technical Analysis of CapitaLand Mall Trust Stock Prices",
         yaxis = list(title = "Closing Price"),
         xaxis = list(title = "Date"))

```